version: '3.8'

services:
  server:
    image: myimage/tests:latest
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "8000:8000"

  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data: